name: AUTO
env:
  PROJECT_NAME: app_repo 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
  pull_request:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  codeStyle:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Python Style Checker
        id: autopep8
        uses: peter-evans/autopep8@v1
        with: 
          args: --ignore E402

  runTests:
    runs-on: ubuntu-latest
    needs: [codeStyle]
    
    steps:
      - uses: actions/checkout@v2
        
      - name: tests
        run: |
          pip install -e '.[test]'
          pip install coverage
          python -m coverage run -m pytest
          python -m coverage report
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [runTests]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Docker build
      run: |
        docker build -t ${{ secrets.USERNAME }}/$PROJECT_NAME:ver_$GITHUB_RUN_NUMBER .
        docker images
        
        
    - name: Upload to docker hub
      run: |
        docker login --username=${{ secrets.DOCKER_LOGIN }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.USERNAME }}/$PROJECT_NAME:ver_$GITHUB_RUN_NUMBER
